In [6]:
import numpy as np

In [8]:
l = np.linspace(10,50,7)
print(l)

[10.         16.66666667 23.33333333 30.         36.66666667 43.33333333
 50.        ]


In [13]:
## create a 4 by 4 array with value 1-16 extract row 2 and col 3
l = np.array([1,2,3])
print(l.shape)

o = np.ones((5,3))
print(o)

j = np.dot(1,0)
print(j)

n = np.arange(1,17).reshape(4,4)
print(n)

(3,)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
import pandas as pd
