In [31]:
lst = [1, 2, 3]
lst[-1:-1] = [99]
print(lst)

[1, 2, 99, 3]


#Numpy


In [32]:
import numpy as np


In [33]:

arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [34]:
zeros = np.zeros((3,3))
one = np.ones((3,3))

print("Zeros Matrix:")

print(zeros)

print("Ones Matrix:")
print(one)

Zeros Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [35]:
even = np.arange(2, 21, 2)

print(even)

[ 2  4  6  8 10 12 14 16 18 20]


In [36]:
values = np.linspace(0, 1, 5)

print(values)

[0.   0.25 0.5  0.75 1.  ]


In [37]:
identity = np.eye(4)

print(identity)

print("Shape:", identity.shape)

print("Size:", identity.size)

print("Dimensions:", identity.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape: (4, 4)
Size: 16
Dimensions: 2


In [38]:
arr = np.array([1, 2, 3, 4, 5], dtype=float)

print(arr)

print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


In [39]:
arr12 = np.arange(10)
print(arr12)
arr12 = arr12+5
print(arr12)
print("multiply",arr12*5)
print("exponent",arr12**2)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
multiply [25 30 35 40 45 50 55 60 65 70]
exponent [ 25  36  49  64  81 100 121 144 169 196]


In [40]:
x = np.arange(6).reshape(3,2)
y = np.arange(2)
print("x is ",x)
print("y is ",y)
print(x+y)
#operation only take place on arrays when they are of same shape or size

x is  [[0 1]
 [2 3]
 [4 5]]
y is  [0 1]
[[0 2]
 [2 4]
 [4 6]]


In [41]:
# comparison operators
x = np.arange(5)
y = np.arange(1,6)
print(x)
print(y)
print(x==y)
print(x>y)
print(x<y)

[0 1 2 3 4]
[1 2 3 4 5]
[False False False False False]
[False False False False False]
[ True  True  True  True  True]


In [42]:
np.random.seed(42) #will generate same value for random.rand
np.random.rand(5) # generates random value b/w 0 to 1 and they are uniform


array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [43]:
np.random.randint(10,20,5) # if u want to generate random value in int format(start,end,size)
np.random.randint(10,50,size=(3,4))

array([[49, 33, 12, 31],
       [11, 33, 39, 47],
       [11, 30, 42, 21]])

In [44]:
lst = [3,4,56,7,9] # if u give just single int it will take it as range
np.random.choice(lst,3,replace= False) # replace use to decide will value will be repeated to not
np.random.choice(10,2, replace= False)

array([9, 5])

In [45]:

np.random.seed(42)
np.random.randint(1,7,size=(1,10))

array([[4, 5, 3, 5, 5, 2, 3, 3, 3, 5]])

In [46]:
np.random.randint(10,50,size=(3,4))

array([[45, 49, 33, 12],
       [31, 11, 33, 39],
       [47, 11, 30, 42]])

In [47]:
lst = ['Aman','Priya','Rahul','Sneha','Vikram']
np.random.choice(lst,replace=False)

np.str_('Rahul')

In [48]:
#class 5
arr = np.array([3,4,5,7]).reshape(1,4)
arr1 = np.array([3,4,5,6]).reshape(4,1)
print(arr + arr1)


[[ 6  7  8 10]
 [ 7  8  9 11]
 [ 8  9 10 12]
 [ 9 10 11 13]]


In [49]:
arr = np.arange(10)
print(arr.shape)
arr1 = arr.reshape(1,-1)
arr2 = arr.reshape(-1,1)
print("row vector",arr1)
print("col vect", arr2)

(10,)
row vector [[0 1 2 3 4 5 6 7 8 9]]
col vect [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [50]:
# row vector is always 2d
arr1 = np.arange(12)
print(arr1.shape)
arr1 = arr1[:,np.newaxis] # newaxis turn 1d to row or col vector but mostly we use -1
print(arr1.shape)

(12,)
(12, 1)


In [51]:
#flatten() vs ravel()
arr = np.arange(12).reshape(4,3)
print(arr)
arr1 = arr.ravel() # shallow copy if u change here it will also change in flatten one
arr1[0] = 99
arr1[2] = 98
arr2 = arr.flatten() # deep copy if u change here only change here
arr2[1] = 100

print("ravel arr",arr1)
print("flatten arr",arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
ravel arr [99  1 98  3  4  5  6  7  8  9 10 11]
flatten arr [ 99 100  98   3   4   5   6   7   8   9  10  11]


In [52]:
a = np.ones((3,4))
b = np.array([10,20,30]).reshape(3,1)
print(a+b)


[[11. 11. 11. 11.]
 [21. 21. 21. 21.]
 [31. 31. 31. 31.]]


In [53]:
a = np.arange(6).reshape(2,3)
b = np.arange(6).reshape(3,2)
print(a+b)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [54]:
a = np.ones((10,10))

# class **6**

In [55]:
#class 6
marks = np.array([92,61,45,78])


In [56]:
marks = np.array([35, 68, 42, 91, 27, 55])
idx = np.where(marks > 50) #just tuple
idx1 = np.where(marks > 50)[0] # array return
print(idx)
print(idx1)

(array([1, 3, 5]),)
[1 3 5]


In [57]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("a*b ", a*b)
print("dot product ", np.dot(a,b))


a*b  [ 4 10 18]
dot product  32


In [58]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[3,5],[5,6],[7,8]])
print(x)
print(x.T)
print(x@x.T)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]


In [59]:
# Create a blank mark sheet for 6 students and 4 subjects, every entry = 0
sheet = np.zeros((6,4), dtype = int)
print(sheet)
# Same size where every student is temporarily given 35
sheet1 = np.full((6,4),35)
print(sheet1)
# Alternate roll numbers from 101 to 130
sheet2 = np.arange(101,131,2)
print(sheet2)
# Split 3 hours into 7 equally spaced time markers
sheet3 = np.linspace(0,3,7)
print(sheet3)
# 5x5 matrix with 10 on diagonal and 0 elsewhere
sheet4 = np.eye(5,5)*10
print(sheet4)
# 4x4 matrix with 100 on diagonal and 35 elsewhere
sheet5 = np.full((4,4),35)
np.fill_diagonal(sheet5,100)
print(sheet5)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]]
[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
[0.  0.5 1.  1.5 2.  2.5 3. ]
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]
[[100  35  35  35]
 [ 35 100  35  35]
 [ 35  35 100  35]
 [ 35  35  35 100]]


### class **7**

In [1]:
# class 7
import pandas as pd


In [61]:
restaurant_data = {
    'table_no' : [12,14,15],
    'Bill_amount' : [1250,890,2400],
    'waiter_name' : ['A','B','C']
}
df = pd.DataFrame(restaurant_data)
print("task 1")
print(df)
print(type(df)) # data in excel type is data frame it is in row and format column

print("task 2")
print(df['Bill_amount']) # to access single row of dataframe
print(type(df['Bill_amount'])) # single column of dataframe is series

print("task 3")
print(df[['table_no','Bill_amount']])
print(type(df[['table_no','Bill_amount']]))


task 1
   table_no  Bill_amount waiter_name
0        12         1250           A
1        14          890           B
2        15         2400           C
<class 'pandas.core.frame.DataFrame'>
task 2
0    1250
1     890
2    2400
Name: Bill_amount, dtype: int64
<class 'pandas.core.series.Series'>
task 3
   table_no  Bill_amount
0        12         1250
1        14          890
2        15         2400
<class 'pandas.core.frame.DataFrame'>


In [62]:
total_bill = [4700,1200,1822,5000]
s = pd.Series(total_bill,index=['mon','tue','wed','fri'])
print(s);
print(type(s))

mon    4700
tue    1200
wed    1822
fri    5000
dtype: int64
<class 'pandas.core.series.Series'>


In [63]:
## assignment
order = {
    'food_name' : ['Pizza','Burger','Pasta','Fries'],
    'Item_count' : [45,30,15,60]
}
df = pd.DataFrame(order)
print(df)
print("pizza count",df.loc[0, 'Item_count'])

  food_name  Item_count
0     Pizza          45
1    Burger          30
2     Pasta          15
3     Fries          60
pizza count 45


In [2]:
df = pd.read_csv("/Users/vedikaagalave/Documents/ml sem3/data/tip.csv") ## read csv

In [66]:
df.head() ## display top 5 row of data

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [67]:
x = df['day']
print(x)

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ... 
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: object


In [68]:
df.head(10) ## will give top 10 data

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
5,25.29,4.71,Male,No,Sun,Dinner,4
6,8.77,2.00,Male,No,Sun,Dinner,2
7,26.88,3.12,Male,No,Sun,Dinner,4
8,15.04,1.96,Male,No,Sun,Dinner,2
9,14.78,3.23,Male,No,Sun,Dinner,2


In [69]:
df.tail() ## bottom data
print(df.tail())

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2


In [70]:
df.sample() ## gives random value from data

,total_bill,tip,sex,smoker,day,time,size
30,9.55,1.45,Male,No,Sat,Dinner,2


In [71]:
df.shape  ## row,col
print(df.columns) ## columss name

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')


In [72]:
df.info() ## dtype and null count of entire data in one shot

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


# class **8**

In [ ]:
df = ("/Users/vedikapd.read_csvagalave/Documents/ml sem3/data/Titanic-Dataset.csv") ## read csv

# class **9**

In [74]:
df.loc[5:10,'total_bill':'time']

KeyError: 'total_bill'

# class **10**

In [76]:
p = pd.read_csv("/Users/vedikaagalave/Documents/ml sem3/data/planets.csv")

In [77]:
## name pclass and fare < 65
df[df['Age']>65][["Pclass","Name","Fare"]]

,Pclass,Name,Fare
33,2,"Wheadon, Mr. Edward H",10.5000
96,1,"Goldschmidt, Mr. George B",34.6542
116,3,"Connors, Mr. Patrick",7.7500
493,1,"Artagaveytia, Mr. Ramon",49.5042
630,1,"Barkworth, Mr. Algernon Henry Wilson",30.0000
672,2,"Mitchell, Mr. Henry Michael",10.5000
745,1,"Crosby, Capt. Edward Gifford",71.0000
851,3,"Svensson, Mr. Johan",7.7750


In [78]:
## how many passenger didn't board southampton
df[~(df['Embarked']=="5")].shape[0]

891

In [79]:
## passenger under 10 or over 70
df[(df['Age'] < 10) | (df['Age'] > 70)].shape[0]

67

In [80]:
## how many passenger travelled in each class
df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [81]:
p.head()

,method,number,orbital_period,mass,distance,year
0,Radial Velocity,1,269.300,7.10,77.40,2006
1,Radial Velocity,1,874.774,2.21,56.95,2008
2,Radial Velocity,1,763.000,2.60,19.84,2011
3,Radial Velocity,1,326.030,19.40,110.62,2007
4,Radial Velocity,1,516.220,10.50,119.47,2009


In [82]:
p.isnull().sum()

method              0
number              0
orbital_period     43
mass              522
distance          227
year                0
dtype: int64

In [83]:
## count the blank in one col
p['mass'].isnull().sum()
## isnull and isna same function

np.int64(522)

In [84]:
df.dropna(subset=['Embarked'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [85]:
## drop blank col how many col servive
df.dropna(axis=1)

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000


In [86]:
p['mass'].fillna(0).isnull().sum()

np.int64(0)

# class **11**

In [87]:
## which passenger paid highest fare in each class
df.loc[df.groupby('Pclass')['Fare'].idxmax(),['Name','Pclass','Fare']]


,Name,Pclass,Fare
258,"Ward, Miss. Anna",1,512.3292
72,"Hood, Mr. Ambrose Jr",2,73.5000
159,"Sage, Master. Thomas Henry",3,69.5500


In [88]:
tip =  pd.read_csv("/Users/vedikaagalave/Documents/ml sem3/data/tip.csv")

In [89]:
## tip_pct col -> avg it per day
tip['tip_pct'] = round(tip['tip']/tip['total_bill']*100,2)
tip.head(2)
tip.groupby('day')['tip_pct'].mean().round(2)

day
Fri     16.99
Sat     15.31
Sun     16.69
Thur    16.13
Name: tip_pct, dtype: float64

In [91]:
## avg fare in each class
round(df.groupby('Pclass')["Fare"].mean(),2)

Pclass
1    84.15
2    20.66
3    13.68
Name: Fare, dtype: float64

In [94]:
## avg age of each port passenger baorded
df.groupby('Parch')["Age"].mean()

Parch
0    32.178503
1    24.422000
2    17.216912
3    33.200000
4    44.500000
5    39.200000
6    43.000000
Name: Age, dtype: float64

# class **12**

In [3]:
tip = pd.read_csv("/Users/vedikaagalave/Documents/ml sem3/data/tip.csv")

In [ ]:
tip.groupby("day")["total_bill"]

In [5]:
tip.groupby("day").agg(
    Bill_count =("total_bill",'size'),
    avg_bill =("total_bill",'mean'),
    avg_tip =("tip",'mean')
)

,Bill_count,avg_bill,avg_tip
day,,,
Fri,19,17.151579,2.734737
Sat,87,20.441379,2.993103
Sun,76,21.410000,3.255132
Thur,62,17.682742,2.771452


In [8]:
## to save your work in csv
summary = pd.read_csv("/Users/vedikaagalave/Documents/ml sem3/data/bookings.csv")
tip

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3
240,27.18,2.00,Female,Yes,Sat,Dinner,2
241,22.67,2.00,Male,Yes,Sat,Dinner,2
242,17.82,1.75,Male,No,Sat,Dinner,2


In [ ]:
smoker_report = tip.groupby("smoker").agg(
    total_bill = ("total_bill",'size'),
    avg_bill = ("total_bill",'mean'),
    avg_tip = ("tip",'mean')
)
smoker_report.reset_index().to_csv("smoker_report.csv")


In [ ]:
## max tip name 
print(tip.groupby("day")['tip'].idxmax())


day
Fri      95
Sat     170
Sun     183
Thur    141
Name: tip, dtype: int64


In [15]:
booking = pd.read_csv("/Users/vedikaagalave/Documents/ml sem3/data/bookings.csv")
print((booking['customer'].str.lower().str.strip()))

0     ravi sharma
1      priya iyer
2     ravi sharma
3      amit kumar
4     priya  iyer
5     ravi sharma
6       sana khan
7      amit kumar
8      vikram rao
9      sana  khan
10     priya iyer
11     vikram rao
Name: customer, dtype: object
